### ISSUE TITLE
Congrats on 1k stars

### ISSUE THREAD

**Issue by JobLeonard** [luajit-remake/luajit-remake#11]
Something a little lighthearted:

![1k stars](https://github.com/luajit-remake/luajit-remake/assets/259840/000e834b-2680-4d9a-9289-a5f59ebd6b31)

Good luck with the project, hope the lack of activity is a sign of other good things happening IRL outside of the view of the digital world.

**Comment by sillycross** [comment]
Thanks. I've been working on the optimizing JIT, it's been a lot of design and redesign, and can't really be split into incremental commits, so there's not much activity here. Hopefully I can get something pushed not in the far future :)
