### ISSUE TITLE
Illegal Instruction error while using the custom LLVM Pass

### ISSUE THREAD

**Issue by zNoctum** [luajit-remake/luajit-remake#17]
Hi i have gotten a Illegal Instruction (Core dumped) while trying to run `python3 ljr-build make release`.
I think the problem is that the Docker container and the LLVM instance in it using AVX2.
To reproduce the bug try the build instructions on a device with a Ivy-Bridge or older CPU.

**Comment by zNoctum** [comment]
a solution would be to utilize the new PassPlugin system in clang

**Comment by sillycross** [comment]
> I think the problem is that the Docker container and the LLVM instance in it using AVX2

That's also what I would guess, but I grepped for `vmov` and `vadd` in the disassembly of the `clang` in the Docker image and didn't find anything. Of course this isn't a complete check, but it suggests that the issue is probably a bit deeper.

I don't have a pre-AVX2 CPU so I can't reproduce the issue. Can you run `python3 ljr-build make debug` to see what happens? This should give you a more readable call stack to see where the crash happens. If it crashes within LLVM then it's probably a LLVM configuration problem.

**Comment by zNoctum** [comment]
<details>
<summary>This is the stack trace for `python3 ljr-build make debug`</summary>
```
[82/539] Generating ../../../../__generated__/debug/generated/deegen_unit_test_ir_accessor.cpp, ../../../../__generated__/debug/generated/deegen_unittest.bytecode_definition_api.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.llvm_constant_parser.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.proven_type_specialization.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.make_call_api_parser.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.bytecode_interpreter_lowering_sanity_1.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.make_call_api_lowering.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.return_value_accessor_api_lowering.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.user_lib_func_api.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.throw_error_api_lowering.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.ic_api_sanity.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.lambda_capture_parser_sanity.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.llvm_effectful_function_tests.cpp.ir.cpp
FAILED: ../../__generated__/debug/generated/deegen_unit_test_ir_accessor.cpp ../../__generated__/debug/generated/deegen_unittest.bytecode_definition_api.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.llvm_constant_parser.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.proven_type_specialization.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.make_call_api_parser.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.bytecode_interpreter_lowering_sanity_1.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.make_call_api_lowering.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.return_value_accessor_api_lowering.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.user_lib_func_api.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.throw_error_api_lowering.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.ic_api_sanity.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.lambda_capture_parser_sanity.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.llvm_effectful_function_tests.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unit_test_ir_accessor.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.bytecode_definition_api.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.llvm_constant_parser.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.proven_type_specialization.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.make_call_api_parser.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.bytecode_interpreter_lowering_sanity_1.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.make_call_api_lowering.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.return_value_accessor_api_lowering.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.user_lib_func_api.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.throw_error_api_lowering.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.ic_api_sanity.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.lambda_capture_parser_sanity.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.llvm_effectful_function_tests.cpp.ir.cpp 
cd /home/u/project/build/debug/annotated/unit_test && /home/u/project/build/debug/annotated/unit_test/package_unit_test_ir '/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./bytecode_definition_api.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./llvm_constant_parser.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./proven_type_specialization.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./make_call_api_parser.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./bytecode_interpreter_lowering_sanity_1.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./make_call_api_lowering.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./return_value_accessor_api_lowering.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./user_lib_func_api.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./throw_error_api_lowering.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./ic_api_sanity.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./lambda_capture_parser_sanity.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./llvm_effectful_function_tests.cpp.o' /home/u/project/__generated__/debug/generated
```
</details>

After doing some digging i think the best solution would be the `preserve_none` CallingConv that is going to be added to LLVM
with Version 19 and then just using the standard LLVM with its readily available binaries (if it is possible to do the custom annotations in another way. In the case that you are interested in this Solution i would be happy to implement this Change.

**Comment by zNoctum** [comment]
if i rerun the command the full output is
<code>-- Configuring done
-- Generating done
-- Build files have been written to: /home/u/project/build/debug
[1/456] Generating ../../../../__generated__/debug/generated/deegen_unit_test_ir_accessor.cpp, ../../../../__generated__/debug/generated/deegen_unittest.bytecode_definition_api.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.llvm_constant_parser.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.proven_type_specialization.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.make_call_api_parser.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.bytecode_interpreter_lowering_sanity_1.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.make_call_api_lowering.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.return_value_accessor_api_lowering.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.user_lib_func_api.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.throw_error_api_lowering.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.ic_api_sanity.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.lambda_capture_parser_sanity.cpp.ir.cpp, ../../../../__generated__/debug/generated/deegen_unittest.llvm_effectful_function_tests.cpp.ir.cpp
FAILED: ../../__generated__/debug/generated/deegen_unit_test_ir_accessor.cpp ../../__generated__/debug/generated/deegen_unittest.bytecode_definition_api.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.llvm_constant_parser.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.proven_type_specialization.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.make_call_api_parser.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.bytecode_interpreter_lowering_sanity_1.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.make_call_api_lowering.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.return_value_accessor_api_lowering.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.user_lib_func_api.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.throw_error_api_lowering.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.ic_api_sanity.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.lambda_capture_parser_sanity.cpp.ir.cpp ../../__generated__/debug/generated/deegen_unittest.llvm_effectful_function_tests.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unit_test_ir_accessor.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.bytecode_definition_api.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.llvm_constant_parser.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.proven_type_specialization.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.make_call_api_parser.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.bytecode_interpreter_lowering_sanity_1.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.make_call_api_lowering.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.return_value_accessor_api_lowering.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.user_lib_func_api.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.throw_error_api_lowering.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.ic_api_sanity.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.lambda_capture_parser_sanity.cpp.ir.cpp /home/u/project/__generated__/debug/generated/deegen_unittest.llvm_effectful_function_tests.cpp.ir.cpp 
cd /home/u/project/build/debug/annotated/unit_test && /home/u/project/build/debug/annotated/unit_test/package_unit_test_ir '/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./bytecode_definition_api.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./llvm_constant_parser.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./proven_type_specialization.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./make_call_api_parser.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./bytecode_interpreter_lowering_sanity_1.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./make_call_api_lowering.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./return_value_accessor_api_lowering.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./user_lib_func_api.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./throw_error_api_lowering.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./ic_api_sanity.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./lambda_capture_parser_sanity.cpp.o;/home/u/project/build/debug/annotated/unit_test/CMakeFiles/deegen_unit_test_ir_sources.dir/./llvm_effectful_function_tests.cpp.o' /home/u/project/__generated__/debug/generated
Illegal instruction (core dumped)
[2/456] Building CXX object annotated/deegen_common_snippets/CMakeFiles/deegen_common_snippet_ir_sources.dir/get_num_variadic_results.cpp.o
[3/456] Building CXX object annotated/deegen_common_snippets/CMakeFiles/deegen_common_snippet_ir_sources.dir/copy_variadic_results_to_arguments.cpp.o
ninja: build stopped: subcommand failed.</code>

**Comment by zNoctum** [comment]
i removed the <code>-msse4 -mbmi1</code> from the CMakeLists.txt and now it compiles maybe it would be a good idea to replace them with <code>-march=native</code>

**Comment by zNoctum** [comment]
> Sorry I'm confused. I see from the log that the crash happened for `package_unit_test_ir`, but I don't see where the stack trace is. Did you forget to paste anything? I also don't see how this is related to the `preserve_none` calling convention you mentioned. Can you elaborate?

i thought the error was in the docker image LLVM so i thought moving to a native LLVM would be the easiest fix.
sorry

**Comment by zNoctum** [comment]
eitherway there was a LLVM assertion that failed
<code>[372/539] Generating ../../../../__generated__/debug/generated/deegen_bytecode_defs.comparison_bytecodes.cpp.s, ../../../../__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.6e7a789514f08fbf5bede84a06fedeae0e66e58e.h
FAILED: ../../__generated__/debug/generated/deegen_bytecode_defs.comparison_bytecodes.cpp.s ../../__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.6e7a789514f08fbf5bede84a06fedeae0e66e58e.h /home/u/project/__generated__/debug/generated/deegen_bytecode_defs.comparison_bytecodes.cpp.s /home/u/project/__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.6e7a789514f08fbf5bede84a06fedeae0e66e58e.h 
cd /home/u/project/build/debug/annotated/bytecodes && /home/u/project/build/debug/deegen/fps --process-bytecode-definition-for-baseline-jit --bytecode-name-table=/home/u/project/__generated__/debug/generated/interpreter_opcode_names.json --bytecode-trait-table=/home/u/project/__generated__/debug/generated/bytecode_opcode_trait_table.json --json-input=/home/u/project/__generated__/debug/generated/bytecode_info.interpreter.comparison_bytecodes.cpp.json --asm-output=/home/u/project/__generated__/debug/generated/deegen_bytecode_defs.comparison_bytecodes.cpp.s --hdr-output=/home/u/project/__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.6e7a789514f08fbf5bede84a06fedeae0e66e58e.h --audit-dir=/home/u/project/__generated__/debug/generated/../audit
deegen/llvm_llc_helper.cpp:71: std::string dast::CompileLLVMModuleImpl(llvm::Module *, llvm::CodeGenFileType, llvm::Reloc::Model, llvm::CodeModel::Model, const std::function<void (llvm::TargetOptions &)> &): Assertion `targetFeatures == targetFeaturesForThisFunc' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/u/project/build/debug/deegen/fps --process-bytecode-definition-for-baseline-jit --bytecode-name-table=/home/u/project/__generated__/debug/generated/interpreter_opcode_names.json --bytecode-trait-table=/home/u/project/__generated__/debug/generated/bytecode_opcode_trait_table.json --json-input=/home/u/project/__generated__/debug/generated/bytecode_info.interpreter.comparison_bytecodes.cpp.json --asm-output=/home/u/project/__generated__/debug/generated/deegen_bytecode_defs.comparison_bytecodes.cpp.s --hdr-output=/home/u/project/__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.6e7a789514f08fbf5bede84a06fedeae0e66e58e.h --audit-dir=/home/u/project/__generated__/debug/generated/../audit
 #0 0x0000000003363783 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/u/project/build/debug/deegen/fps+0x3363783)
 #1 0x000000000336168e llvm::sys::RunSignalHandlers() (/home/u/project/build/debug/deegen/fps+0x336168e)
 #2 0x0000000003363b0f SignalHandler(int) Signals.cpp:0:0
 #3 0x00007bbf27e0e420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007bbf278b100b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007bbf27890859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x0000000000456c34 (/home/u/project/build/debug/deegen/fps+0x456c34)
 #7 0x00000000004fed76 dast::CompileLLVMModuleImpl[abi:cxx11](llvm::Module*, llvm::CodeGenFileType, llvm::Reloc::Model, llvm::CodeModel::Model, std::function<void (llvm::TargetOptions&)> const&) build/debug/deegen/llvm_llc_helper.cpp:71:13
 #8 0x00000000004fe6bf dast::CompileLLVMModuleToAssemblyFile[abi:cxx11](llvm::Module*, llvm::Reloc::Model, llvm::CodeModel::Model) build/debug/deegen/llvm_llc_helper.cpp:134:12
 #9 0x000000000049bd80 FPS_ProcessBytecodeDefinitionForBaselineJit() build/debug/deegen/fps_process_bytecode_definition_for_baseline_jit.cpp:397:32
#10 0x000000000044e868 main build/debug/deegen/fps_main.cpp:45:9
#11 0x00007bbf27892083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#12 0x000000000044e60e _start (/home/u/project/build/debug/deegen/fps+0x44e60e)
Aborted (core dumped)
[373/539] Generating ../../../../__generated__/debug/generated/deegen_bytecode_defs.arithmetic_bytecodes.cpp.s, ../../../../__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.d9ea11a5c987ec4ea4ea889142895cf086757a95.h
FAILED: ../../__generated__/debug/generated/deegen_bytecode_defs.arithmetic_bytecodes.cpp.s ../../__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.d9ea11a5c987ec4ea4ea889142895cf086757a95.h /home/u/project/__generated__/debug/generated/deegen_bytecode_defs.arithmetic_bytecodes.cpp.s /home/u/project/__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.d9ea11a5c987ec4ea4ea889142895cf086757a95.h 
cd /home/u/project/build/debug/annotated/bytecodes && /home/u/project/build/debug/deegen/fps --process-bytecode-definition-for-baseline-jit --bytecode-name-table=/home/u/project/__generated__/debug/generated/interpreter_opcode_names.json --bytecode-trait-table=/home/u/project/__generated__/debug/generated/bytecode_opcode_trait_table.json --json-input=/home/u/project/__generated__/debug/generated/bytecode_info.interpreter.arithmetic_bytecodes.cpp.json --asm-output=/home/u/project/__generated__/debug/generated/deegen_bytecode_defs.arithmetic_bytecodes.cpp.s --hdr-output=/home/u/project/__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.d9ea11a5c987ec4ea4ea889142895cf086757a95.h --audit-dir=/home/u/project/__generated__/debug/generated/../audit
[ERROR] Stencil generation introduced unknown global 'floor'!PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/u/project/build/debug/deegen/fps --process-bytecode-definition-for-baseline-jit --bytecode-name-table=/home/u/project/__generated__/debug/generated/interpreter_opcode_names.json --bytecode-trait-table=/home/u/project/__generated__/debug/generated/bytecode_opcode_trait_table.json --json-input=/home/u/project/__generated__/debug/generated/bytecode_info.interpreter.arithmetic_bytecodes.cpp.json --asm-output=/home/u/project/__generated__/debug/generated/deegen_bytecode_defs.arithmetic_bytecodes.cpp.s --hdr-output=/home/u/project/__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.d9ea11a5c987ec4ea4ea889142895cf086757a95.h --audit-dir=/home/u/project/__generated__/debug/generated/../audit
 #0 0x0000000003363783 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/u/project/build/debug/deegen/fps+0x3363783)
 #1 0x000000000336168e llvm::sys::RunSignalHandlers() (/home/u/project/build/debug/deegen/fps+0x336168e)
 #2 0x0000000003363b0f SignalHandler(int) Signals.cpp:0:0
 #3 0x000079007a4e6420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x0000790079f8900b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x0000790079f68859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00000000005f6147 dast::DeegenStencilCodegenResult::GenerateCodegenLogicLLVMModule(llvm::Module*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) build/debug/deegen/deegen_stencil_creator.cpp:0:21
 #7 0x0000000000627c36 dast::DeegenBytecodeBaselineJitInfo::Create(dast::BytecodeIrInfo&, dast::DeegenGlobalBytecodeTraitAccessor const&) build/debug/deegen/deegen_baseline_jit_codegen_logic_creator.cpp:512:54
 #8 0x000000000063cbde dast::DeegenProcessBytecodeForBaselineJitResult::Create(dast::BytecodeIrInfo*, dast::DeegenGlobalBytecodeTraitAccessor const&) build/debug/deegen/deegen_process_bytecode_for_baseline_jit.cpp:14:29
 #9 0x000000000049903c FPS_ProcessBytecodeDefinitionForBaselineJit() build/debug/deegen/fps_process_bytecode_definition_for_baseline_jit.cpp:84:57
#10 0x000000000044e868 main build/debug/deegen/fps_main.cpp:45:9
#11 0x0000790079f6a083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#12 0x000000000044e60e _start (/home/u/project/build/debug/deegen/fps+0x44e60e)
Aborted (core dumped)
[374/539] Generating ../../../../__generated__/debug/generated/deegen_bytecode_defs.call_bytecodes.cpp.s, ../../../../__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.3b158f4a27ab43750880c010afa80297d497dbec.h
FAILED: ../../__generated__/debug/generated/deegen_bytecode_defs.call_bytecodes.cpp.s ../../__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.3b158f4a27ab43750880c010afa80297d497dbec.h /home/u/project/__generated__/debug/generated/deegen_bytecode_defs.call_bytecodes.cpp.s /home/u/project/__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.3b158f4a27ab43750880c010afa80297d497dbec.h 
cd /home/u/project/build/debug/annotated/bytecodes && /home/u/project/build/debug/deegen/fps --process-bytecode-definition-for-baseline-jit --bytecode-name-table=/home/u/project/__generated__/debug/generated/interpreter_opcode_names.json --bytecode-trait-table=/home/u/project/__generated__/debug/generated/bytecode_opcode_trait_table.json --json-input=/home/u/project/__generated__/debug/generated/bytecode_info.interpreter.call_bytecodes.cpp.json --asm-output=/home/u/project/__generated__/debug/generated/deegen_bytecode_defs.call_bytecodes.cpp.s --hdr-output=/home/u/project/__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.3b158f4a27ab43750880c010afa80297d497dbec.h --audit-dir=/home/u/project/__generated__/debug/generated/../audit
deegen/llvm_llc_helper.cpp:71: std::string dast::CompileLLVMModuleImpl(llvm::Module *, llvm::CodeGenFileType, llvm::Reloc::Model, llvm::CodeModel::Model, const std::function<void (llvm::TargetOptions &)> &): Assertion `targetFeatures == targetFeaturesForThisFunc' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/u/project/build/debug/deegen/fps --process-bytecode-definition-for-baseline-jit --bytecode-name-table=/home/u/project/__generated__/debug/generated/interpreter_opcode_names.json --bytecode-trait-table=/home/u/project/__generated__/debug/generated/bytecode_opcode_trait_table.json --json-input=/home/u/project/__generated__/debug/generated/bytecode_info.interpreter.call_bytecodes.cpp.json --asm-output=/home/u/project/__generated__/debug/generated/deegen_bytecode_defs.call_bytecodes.cpp.s --hdr-output=/home/u/project/__generated__/debug/generated/deegen_baseline_jit_bytecode_traits.3b158f4a27ab43750880c010afa80297d497dbec.h --audit-dir=/home/u/project/__generated__/debug/generated/../audit
 #0 0x0000000003363783 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/u/project/build/debug/deegen/fps+0x3363783)
 #1 0x000000000336168e llvm::sys::RunSignalHandlers() (/home/u/project/build/debug/deegen/fps+0x336168e)
 #2 0x0000000003363b0f SignalHandler(int) Signals.cpp:0:0
 #3 0x00007c836f7eb420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007c836f28e00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007c836f26d859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x0000000000456c34 (/home/u/project/build/debug/deegen/fps+0x456c34)
 #7 0x00000000004fed76 dast::CompileLLVMModuleImpl[abi:cxx11](llvm::Module*, llvm::CodeGenFileType, llvm::Reloc::Model, llvm::CodeModel::Model, std::function<void (llvm::TargetOptions&)> const&) build/debug/deegen/llvm_llc_helper.cpp:71:13
 #8 0x00000000004fe6bf dast::CompileLLVMModuleToAssemblyFile[abi:cxx11](llvm::Module*, llvm::Reloc::Model, llvm::CodeModel::Model) build/debug/deegen/llvm_llc_helper.cpp:134:12
 #9 0x000000000049bd80 FPS_ProcessBytecodeDefinitionForBaselineJit() build/debug/deegen/fps_process_bytecode_definition_for_baseline_jit.cpp:397:32
#10 0x000000000044e868 main build/debug/deegen/fps_main.cpp:45:9
#11 0x00007c836f26f083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#12 0x000000000044e60e _start (/home/u/project/build/debug/deegen/fps+0x44e60e)
Aborted (core dumped)
ninja: build stopped: subcommand failed.</code>

**Comment by sillycross** [comment]
The failed assertion is a bit unexpected for me. Just as a sanity check, can you try to run a fresh build? 

I assume you have modified your CMakefile to remove `-mbmi1` (but not anything else). Then run 
```
python3 ljr-build make release clean
python3 ljr-build make release
```
and check if you still have error.

**Comment by sillycross** [comment]
I think I understood the problem. `deegen/invoke_clang_helper.cpp` has another place where it invokes clang with `-mbmi -msse4`. You need to make correspond changes to the flag in that file, so it is consistent with your CMakefile.

**Comment by sillycross** [comment]
Anyway if you care about performance you'd better get a newer CPU.. You can easily get a low-end 2022 CPU at ~$50 that performs way better than your pre-2013 CPU..

**Comment by zNoctum** [comment]
i am running a old thinkpad. and it has sse4. i just disabled both. it works without floor as long as sse4 is enabled and the using the laptop for compilation is only a temporary thing

**Comment by zNoctum** [comment]
should i make a pull with some info for building on old hardware summing this issue up?

**Comment by sillycross** [comment]
You are welcomed to describe the fixes you made here for other people. :)
Given that this project is still far from production ready, at the time it gets any real-world use, pre-2013 CPUs should have become completely obsolete so I don't think a pull request to specifically deal with this issue is worth it (and it will take a lot of efforts to fix the unit tests since currently all of these CPU flags are directly reflected in LLVM IR, which are checked by tests).

**Comment by zNoctum** [comment]
the i think just referring to this issue will be enough
