### ISSUE TITLE
Lua 5.3/5.4 please!

### ISSUE THREAD

**Issue by socketpair** [luajit-remake/luajit-remake#5]
Or, better, support different versions using some key.

**Comment by sillycross** [comment]
This is a research project, and it is far from production-ready even for Lua 5.1. So while Deegen is intended to be a generic meta-compiler, it is still very far from targeting newer Lua versions.

**Comment by Rustbelther0** [comment]
Well ya gotta fly before ya can walk if I can drum up some other interested party's ideally some that know assembly better then I do think be easier then starting from scratch and be honest I always use 5.1 but libarys are old or unavailable and idk it's time
