### ISSUE TITLE
Terra

### ISSUE THREAD

**Issue by luveti** [luajit-remake/luajit-remake#6]
Hi! This project looks really promising. It's great to see a potential future replacement for an aging LuaJIT.

I've recently started using [Terra](https://terralang.org/) mostly for its ability to write functions with predictable performance in a Lua like language.

Terras killer feature is that it's an LLVM IR generator meta-programmed with Lua.

With that said, I have a couple questions:

1. Were you aware of Terras existence?
2. If so, have you considered this for Deegen? I wonder if this could open up new possiblities that are not possible/hard to implement with C++ and its macro system. Or even greatly reduce it's code size.

I could see this project being very beneficial to Terra, as it currently uses LuaJIT. Maybe it can be beneficial to this project in some way :)

**Comment by sillycross** [comment]
Thanks for the question.

> Were you aware of Terras existence?

I am aware of Terra, though never used it personally. 
In fact, you can think of our meta-approach as something analogous to Terra already -- it is a level of indirection that allows you to do all sort of hacks on the LLVM IR. 

> If so, have you considered this for Deegen?

It is unclear to me how Terra could be helpful to Deegen. The bytecode definitions in Deegen need precise C++ semantics, has a tight integration with the C++ runtime, and uses low level hacks like bit-casting between double and integer all the time, so it makes more sense to directly implement them in C++.
